<a href="https://colab.research.google.com/github/marongkang/MLeveryday/blob/main/MLEveryday10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch
>基础知识  
>张量Tensor




In [ ]:
!pip3 install torch

In [ ]:
import torch
import pandas as pd
import numpy as np

x=torch.Tensor(3,4)

print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: {}".format(x))

Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: tensor([[1.2683e-22, 3.0911e-41, 3.7835e-44, 0.0000e+00],
        [       nan, 3.0911e-41, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])


In [ ]:
#随机张量
x=torch.randn(3,4)
#randn为正态分布,rand为均匀分布
print(x)

tensor([[ 1.0920, -0.4168,  0.0802,  0.1542],
        [-1.1902,  1.0000, -0.3324, -0.2378],
        [-1.5147,  0.2191,  0.2485, -1.4033]])


In [ ]:
#1张量和0张量
x=torch.zeros(3,4)
print(x)

x=torch.ones(3,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
#List->Tensor
list_x=[[1,2,3],[4,5,6]]
x=torch.Tensor(list_x)
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
#numpy array->Tensor
np_array=np.random.randn(3,4)
x=torch.from_numpy(np_array)
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Size: torch.Size([3, 4])
Values: 
tensor([[-1.0440,  0.2810,  2.2952,  1.5398],
        [-1.8866, -0.5835, -0.3785, -0.6561],
        [ 0.1972, -0.0536, -0.1026, -1.0373]], dtype=torch.float64)


In [ ]:
#改变张量类型(默认为float)
x=torch.Tensor(3,4)
print("type: {}".format(x.type()))
x=x.int()
print("type: {}".format(x.type()))
x=x.double()
print("type: {}".format(x.type()))

type: torch.FloatTensor
type: torch.IntTensor
type: torch.DoubleTensor


In [ ]:
#张量计算
x=torch.Tensor([[1,2],[3,4],[5,6]])
print("x:\n{0} \n size:{1}".format(x,x.shape))
y=torch.tensor([[1,2,3],[4,5,6]])
print("y:\n{0} \n size:{1}".format(y,y.shape))
#加法
z=x+x
print("z=x+y:\n{0}\n size: \n{1}".format(z,z.shape))

y=y.float()
print(x.type(),y.type())
z=torch.mm(x,y)
print("z=xy:\n{0}\n size: \n{1}".format(z,z.shape))

x:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 
 size:torch.Size([3, 2])
y:
tensor([[1, 2, 3],
        [4, 5, 6]]) 
 size:torch.Size([2, 3])
z=x+y:
tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]])
 size: 
torch.Size([3, 2])
torch.FloatTensor torch.FloatTensor
z=xy:
tensor([[ 9., 12., 15.],
        [19., 26., 33.],
        [29., 40., 51.]])
 size: 
torch.Size([3, 3])


In [ ]:
#转置

z=torch.t(z)
print("z:\n{}".format(z))

z:
tensor([[ 9., 19., 29.],
        [12., 26., 40.],
        [15., 33., 51.]])


In [ ]:
print(z.shape)
#z=torch.rand(3,3)
#z=torch.t(z)

#z=z.view(1,9)#view不可以接在t后面,不知道为什么
#z
z=z.reshape(1,9)#但是reshape可以
z

torch.Size([3, 3])


tensor([[ 9., 19., 29., 12., 26., 40., 15., 33., 51.]])

reshape和view的区别  
  >view是浅拷贝,reshape是深拷贝,一般情况下用reshape,不容易出问题  
  >如果是对内存有限制,用view

#reshaping注意点

In [ ]:
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("size:{}".format(x.shape))
print("value:{}".format(x))

#-1表示不确定的输入,如(2,-1),表示两行,列数不确定
a=x.view(x.size(1),-1)
print("size:{}".format(a.shape))
print("value:{}".format(a))

b=x.transpose(0,1).contiguous()
#transpose()进行转置,contiguous指在内存中连续存储,此相当于强制拷贝一份tensor,布局与从头创建一样
print("size:{}".format(b.shape))
print("value:{}".format(b))

c=b.view(b.size(0),-1)
print("size:{}".format(b.shape))
print("value:{}".format(b))

size:torch.Size([2, 3, 4])
value:tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])
size:torch.Size([3, 8])
value:tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])
size:torch.Size([3, 2, 4])
value:tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])
size:torch.Size([3, 2, 4])
value:tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


In [ ]:
#维度操作
x=torch.randn(2,3)
print("values:{}".format(x))

#类似与压缩维度,把这个tensor拍扁了
#按列求和
y=torch.sum(x,dim=0)
print("values:{}".format(y))

#按行求和
z=torch.sum(x,dim=1)
print("values:{}".format(z))

values:tensor([[ 0.7561,  0.7932, -0.9009],
        [ 1.2318, -0.4245, -1.6101]])
values:tensor([ 1.9879,  0.3687, -2.5110])
values:tensor([ 0.6483, -0.8028])


#索引,切片和级联

In [ ]:
x=torch.randn(3,4)
print("values:{}".format(x))
print("values:{}".format(x[:2]))
print("values:{}".format(x[:1,1:3]))

values:tensor([[ 0.4125, -0.5709, -1.0987, -0.2900],
        [ 1.6627, -1.3074, -0.4679, -0.3407],
        [ 0.1489,  0.2246,  1.0744,  0.0704]])
values:tensor([[ 0.4125, -0.5709, -1.0987, -0.2900],
        [ 1.6627, -1.3074, -0.4679, -0.3407]])
values:tensor([[-0.5709, -1.0987]])


In [ ]:
#选择维度索引
x=torch.randn(4,4)
print("values:{}".format(x))
col_indices=torch.LongTensor([1,3])
chosen=torch.index_select(x,dim=1,index=col_indices)#第一列和第三列
print("values:{}".format(chosen))
row_indices=torch.LongTensor([0,2])
chosen=x[row_indices,col_indices]
print("values:{}".format(chosen))#x[0,1]和x[2,3]


values:tensor([[-0.4628,  0.0076, -1.3349,  0.0450],
        [ 0.0848, -0.4872,  0.3861, -0.9295],
        [-0.4373,  0.2518,  0.6980, -1.1888],
        [ 0.4572, -0.6718, -0.0328, -0.9404]])
values:tensor([[ 0.0076,  0.0450],
        [-0.4872, -0.9295],
        [ 0.2518, -1.1888],
        [-0.6718, -0.9404]])
values:tensor([ 0.0076, -1.1888])


In [ ]:
#级联concatenate
x=torch.randn(2,3)
print("values:{}".format(x))
y=torch.cat([x,x],dim=0)
print("values:{}".format(y))

values:tensor([[-1.4428, -1.2781,  0.3531],
        [-0.0763,  1.3093, -2.1142]])
values:tensor([[-1.4428, -1.2781,  0.3531],
        [-0.0763,  1.3093, -2.1142],
        [-1.4428, -1.2781,  0.3531],
        [-0.0763,  1.3093, -2.1142]])


#梯度

In [ ]:
#含gradient的张量
x=torch.randn(2,3,requires_grad=True)
print("value:{}".format(x))
y=3*x+1
print("values:{}".format(y))
z=y.mean()
print("z values:{}".format(z))
z.backward()
print("z values:{}".format(z))

print("x values:\n{}".format(x))
print("x grad:{}\n".format(x.grad))

value:tensor([[-0.2775,  1.3935,  1.9759],
        [-0.1881,  0.2878,  0.2088]], requires_grad=True)
values:tensor([[0.1675, 5.1806, 6.9277],
        [0.4358, 1.8633, 1.6263]], grad_fn=<AddBackward0>)
z values:2.700218915939331
z values:2.700218915939331
x values:
tensor([[-0.2775,  1.3935,  1.9759],
        [-0.1881,  0.2878,  0.2088]], requires_grad=True)
x grad:tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])



*  $y=3*x+1$
*  $z=∑y/N$
*  $\frac{∂z}{∂x}=\frac{∂z}{∂y}\frac{∂y}{∂x}=\frac{1}{N}*3=0.5$

#CUDA张量
买不起显卡,暂时没有