<a href="https://colab.research.google.com/github/marongkang/MLeveryday/blob/main/MLEveryday3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ML** **day3** 
>今天的目标是 NumPy

In [ ]:
import numpy as np

np.random.seed(seed=1234)

# 标量（scalars）
x = np.array(6)
print ("x: ",x)        #输出x
print("x ndim: ",x.ndim)    #x的维度
print("x shape:",x.shape)    #表示数组形状（shape）的元组，表示各维度大小的元组
print("x size: ",x.size)    #表示数组总元素数量
print ("x dtype: ",x.dtype)  #表示数组内元素的数据类型

# 一维数组(array) 
x = np.array([1,2,3,4,5])
print("x :",x)
print("x ndim",x.ndim)
print("x shape:",x.shape)
print("x size:" ,x.size)
print("x dtype:",x.dtype)

# 二维数组

x = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print("x :",x)
print("x ndim",x.ndim)
print("x shape:",x.shape)
print("x size:" ,x.size)
print("x dtype:",x.dtype)

# 三维数组(矩阵Matrix)
x = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print("x :",x)
print("x ndim",x.ndim)
print("x shape:",x.shape)
print("x size:" ,x.size)
print("x dtype:",x.dtype)

#！！！！当n维数组内的元素无法完全填充数组时，会自动转变为list类型


x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64
x : [1 2 3 4 5]
x ndim 1
x shape: (5,)
x size: 5
x dtype: int64
x : [[1 2 3]
 [4 5 6]
 [7 8 9]]
x ndim 2
x shape: (3, 3)
x size: 9
x dtype: int64
x : [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
x ndim 3
x shape: (2, 3, 3)
x size: 18
x dtype: int64


常用函数

In [ ]:
###########################函数######################
#np.zeros(shape, dtype=float, order='C') 
#返回形状为shape ，数据类型为dtype的由0填充的数组
#order:可选参数，C代表与c语言类似，行优先；F代表列优先
print("zeros: ",np.zeros((2,3,4), dtype=int))


#np.ones()
#用法同上，由 1 填充
print("ones: ",np.ones((2,3,4), dtype=int))

#np.eye(N,M=None, k=0, dtype=<type 'float'>)
#生成对角矩阵，N：行数，M:列数（默认等于N)
#k:对角线的下标，默认为0表示的是主对角线，负数表示的是低对角，正数表示的是高对角。
print("eye: ",np.eye(3,k=0))

#np.random.random(size=None) 随机获取[0，1.0)的浮点数
np.random.seed(seed=2)
print("random",np.random.random((2,2)))
#不改变seed的情况下，每次运行结果都是一样的




zeros:  [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
ones:  [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
eye:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
random [[0.4359949  0.02592623]
 [0.54966248 0.43532239]]


索引(index)

In [ ]:
#跟list的操作差不多
x=np.array([1,2,3])
print(x[0],x[1],x[2])


#切片
x=np.array([[1,2,3],[4,5,6]])
print(x[:,:])
print(x[:,1:2])
print(x[0:1,:])

#使用数组进行索引
row=np.array()

1 2 3
[[1 2 3]
 [4 5 6]]
[[2]
 [5]]
[[1 2 3]]
