In [3]:
import numpy as np
import copy
import queue

In [4]:
x = np.array([[1,1,1],[2,2,2],[3,3,3]])
y = np.array([[1,2,3],
              [4,5,6],
              [7,0,8]])

In [32]:
target = np.array([[1,2,3],
                   [4,5,6],
                   [7,0,8]])

class Matrix(object):
    def __init__(self,init_state:np.array):
        self.matrix_ = init_state
        self.zero_x_ = np.argwhere(init_state == 0)[0][0]
        self.zero_y_ = np.argwhere(init_state == 0)[0][1]
        self.depth = 0

    def __lt__(self, other): # 反转大小比较结果，用于实现小顶堆
        return self.f_n() < other.f_n()

    def move_up(self):
        if self.zero_x_ == 0:
            return False
        tmp = self.matrix_[self.zero_x_ - 1][self.zero_y_]
        self.matrix_[self.zero_x_ - 1][self.zero_y_] = 0
        self.matrix_[self.zero_x_][self.zero_y_] = tmp
        self.zero_x_ -= 1
        return True
    def move_down(self):
        if self.zero_x_ == 2:
            return False
        tmp = self.matrix_[self.zero_x_ + 1][self.zero_y_]
        self.matrix_[self.zero_x_ + 1][self.zero_y_] = 0
        self.matrix_[self.zero_x_][self.zero_y_] = tmp
        self.zero_x_ += 1
        return True
    def move_left(self):
        if self.zero_y_ == 0:
            return False
        print(self.zero_x_,self.zero_y_)
        self.matrix_[self.zero_x_][self.zero_y_ - 1], self.matrix_[self.zero_x_][self.zero_y_] \
            = self.matrix_[self.zero_x_][self.zero_y_], self.matrix_[self.zero_x_][self.zero_y_ - 1]
        self.zero_y_ -= 1
        print(self.zero_x_,self.zero_y_)
        return True
    def move_right(self):
        if self.zero_y_ == 2:
            return False
        tmp = self.matrix_[self.zero_x_ - 1][self.zero_y_]
        self.matrix_[self.zero_x_][self.zero_y_ + 1] = 0
        self.matrix_[self.zero_x_][self.zero_y_] = tmp
        self.zero_y_ += 1
        return True
    def w_n(self):
        return 9 - np.sum(self.matrix_ == target)
    def d_n(self):
        return self.depth
    def f_n(self):
        return  self.w_n() + self.d_n()
    def __repr__(self):
        print(self.matrix_)
        return "depth: " + str(self.depth) + "\n"

In [33]:
matrix = Matrix(np.array([[1, 2, 3],
                 [4, 0, 6],
                 [7, 8, 5]]))

In [34]:
matrix_left = copy.deepcopy(matrix)
matrix_left.move_left()

1 1
1 0


True

In [35]:
matrix

[[1 2 3]
 [4 0 6]
 [7 8 5]]


depth: 0

In [31]:
matrix_left

[[1, 2, 3], [4, 0, 6], [8, 7, 5]]


depth: 0

In [ ]:
[[1, 0, 3],
[4, 2, 6],
[7, 5, 8]]